//
//  OutputItem.swift
//  OpenAI
//
//  Created by Oleksii Nezhyborets on 15.04.2025.
//

import Foundation

/// Improved interface to use instead of generated `Components.Schemas.OutputItem`
/// When editing the list of tool calls - also check Tool type if the list of tools should be updated
public enum OutputItem: Codable, Hashable, Sendable {
    public typealias Schemas = Components.Schemas

    /// An output message from the model.
    case outputMessage(Schemas.OutputMessage)
    /// The results of a file search tool call. See the
    /// [file search guide](https://platform.openai.com/docs/guides/tools-file-search) for more information.
    case fileSearchToolCall(Schemas.FileSearchToolCall)
    /// A tool call to run a function. See the
    /// [function calling guide](https://platform.openai.com/docs/guides/function-calling) for more information.
    case functionToolCall(Schemas.FunctionToolCall)
    /// The output resource of a function tool call.
    case functionToolCallOutputResource(Schemas.FunctionToolCallOutputResource)
    /// The results of a web search tool call. See the
    /// [web search guide](https://platform.openai.com/docs/guides/tools-web-search) for more information.
    case webSearchToolCall(WebSearchToolCall)
    /// A tool call to a computer use tool. See the
    /// [computer use guide](https://platform.openai.com/docs/guides/tools-computer-use) for more information.
    case computerToolCall(Schemas.ComputerToolCall)
    /// The output resource of a computer use tool call.
    case computerToolCallOutputResource(Schemas.ComputerToolCallOutputResource)
    /// A description of the chain of thought used by a reasoning model while generating a response.
    case reasoning(Schemas.ReasoningItem)
    /// A program item generated by the model.
    case program(Schemas.Program)
    /// The output of a program item.
    case programOutput(Schemas.ProgramOutput)
    /// A tool search call.
    case toolSearchCall(Schemas.ToolSearchCall)
    /// The output of a tool search call.
    case toolSearchOutput(Schemas.ToolSearchOutput)
    /// The additional tools made available for a request.
    case additionalTools(Schemas.AdditionalTools)
    /// A compaction item generated by the `v1/responses/compact` API.
    case compactionBody(Schemas.CompactionBody)
    /// An image generation request made by the model.
    case imageGenerationCall(Schemas.ImageGenToolCall)
    /// A tool call to run code.
    case codeInterpreterToolCall(Schemas.CodeInterpreterToolCall)
    /// A tool call to run a command on the local shell.
    case localShellCall(Schemas.LocalShellToolCall)
    /// The output of a local shell tool call.
    case localShellToolCallOutput(Schemas.LocalShellToolCallOutput)
    /// A tool call that executes one or more shell commands in a managed environment.
    case functionShellCall(Schemas.FunctionShellCall)
    /// The output of a shell tool call that was emitted.
    case functionShellCallOutput(Schemas.FunctionShellCallOutput)
    /// A tool call that applies file diffs by creating, deleting, or updating files.
    case applyPatchToolCall(Schemas.ApplyPatchToolCall)
    /// The output emitted by an apply patch tool call.
    case applyPatchToolCallOutput(Schemas.ApplyPatchToolCallOutput)
    /// An invocation of a tool on an MCP server.
    case mcpToolCall(Schemas.MCPToolCall)
    /// A list of tools available on an MCP server.
    case mcpListTools(Schemas.MCPListTools)
    /// A request for human approval of a tool invocation.
    case mcpApprovalRequest(Schemas.MCPApprovalRequest)
    /// A response to an MCP approval request.
    case mcpApprovalResponseResource(Schemas.MCPApprovalResponseResource)
    /// A call to a custom tool created by the model.
    case customToolCall(Schemas.CustomToolCall)
    /// The output resource of a custom tool call.
    case customToolCallOutputResource(Schemas.CustomToolCallOutputResource)

    private enum DiscriminatorCodingKeys: String, CodingKey {
        case type
    }

    public init(from decoder: any Decoder) throws {
        // WebSearchToolCall's `action` is decoded leniently (see that type's doc comment), so it's
        // handled before delegating to the generated, spec-strict `Schemas.OutputItem` decoding.
        let discriminatorContainer = try decoder.container(keyedBy: DiscriminatorCodingKeys.self)
        let discriminator = try discriminatorContainer.decode(String.self, forKey: .type)
        switch discriminator {
        case "WebSearchToolCall", "#/components/schemas/WebSearchToolCall", "web_search_call":
            self = .webSearchToolCall(try .init(from: decoder))
            return
        default:
            break
        }

        let generated = try Schemas.OutputItem(from: decoder)
        switch generated {
        case .outputMessage(let value):
            self = .outputMessage(value)
        case .fileSearchToolCall(let value):
            self = .fileSearchToolCall(value)
        case .functionToolCall(let value):
            self = .functionToolCall(value)
        case .functionToolCallOutputResource(let value):
            self = .functionToolCallOutputResource(value)
        case .webSearchToolCall(let value):
            self = .webSearchToolCall(WebSearchToolCall(value))
        case .computerToolCall(let value):
            self = .computerToolCall(value)
        case .computerToolCallOutputResource(let value):
            self = .computerToolCallOutputResource(value)
        case .reasoningItem(let value):
            self = .reasoning(value)
        case .program(let value):
            self = .program(value)
        case .programOutput(let value):
            self = .programOutput(value)
        case .toolSearchCall(let value):
            self = .toolSearchCall(value)
        case .toolSearchOutput(let value):
            self = .toolSearchOutput(value)
        case .additionalTools(let value):
            self = .additionalTools(value)
        case .compactionBody(let value):
            self = .compactionBody(value)
        case .imageGenToolCall(let value):
            self = .imageGenerationCall(value)
        case .codeInterpreterToolCall(let value):
            self = .codeInterpreterToolCall(value)
        case .localShellToolCall(let value):
            self = .localShellCall(value)
        case .localShellToolCallOutput(let value):
            self = .localShellToolCallOutput(value)
        case .functionShellCall(let value):
            self = .functionShellCall(value)
        case .functionShellCallOutput(let value):
            self = .functionShellCallOutput(value)
        case .applyPatchToolCall(let value):
            self = .applyPatchToolCall(value)
        case .applyPatchToolCallOutput(let value):
            self = .applyPatchToolCallOutput(value)
        case .mcpToolCall(let value):
            self = .mcpToolCall(value)
        case .mcpListTools(let value):
            self = .mcpListTools(value)
        case .mcpApprovalRequest(let value):
            self = .mcpApprovalRequest(value)
        case .mcpApprovalResponseResource(let value):
            self = .mcpApprovalResponseResource(value)
        case .customToolCall(let value):
            self = .customToolCall(value)
        case .customToolCallOutputResource(let value):
            self = .customToolCallOutputResource(value)
        }
    }

    public func encode(to encoder: any Encoder) throws {
        switch self {
        case .outputMessage(let value):
            try value.encode(to: encoder)
        case .fileSearchToolCall(let value):
            try value.encode(to: encoder)
        case .functionToolCall(let value):
            try value.encode(to: encoder)
        case .functionToolCallOutputResource(let value):
            try value.encode(to: encoder)
        case .webSearchToolCall(let value):
            try value.encode(to: encoder)
        case .computerToolCall(let value):
            try value.encode(to: encoder)
        case .computerToolCallOutputResource(let value):
            try value.encode(to: encoder)
        case .reasoning(let value):
            try value.encode(to: encoder)
        case .program(let value):
            try value.encode(to: encoder)
        case .programOutput(let value):
            try value.encode(to: encoder)
        case .toolSearchCall(let value):
            try value.encode(to: encoder)
        case .toolSearchOutput(let value):
            try value.encode(to: encoder)
        case .additionalTools(let value):
            try value.encode(to: encoder)
        case .compactionBody(let value):
            try value.encode(to: encoder)
        case .imageGenerationCall(let value):
            try value.encode(to: encoder)
        case .codeInterpreterToolCall(let value):
            try value.encode(to: encoder)
        case .localShellCall(let value):
            try value.encode(to: encoder)
        case .localShellToolCallOutput(let value):
            try value.encode(to: encoder)
        case .functionShellCall(let value):
            try value.encode(to: encoder)
        case .functionShellCallOutput(let value):
            try value.encode(to: encoder)
        case .applyPatchToolCall(let value):
            try value.encode(to: encoder)
        case .applyPatchToolCallOutput(let value):
            try value.encode(to: encoder)
        case .mcpToolCall(let value):
            try value.encode(to: encoder)
        case .mcpListTools(let value):
            try value.encode(to: encoder)
        case .mcpApprovalRequest(let value):
            try value.encode(to: encoder)
        case .mcpApprovalResponseResource(let value):
            try value.encode(to: encoder)
        case .customToolCall(let value):
            try value.encode(to: encoder)
        case .customToolCallOutputResource(let value):
            try value.encode(to: encoder)
        }
    }
}
