//
//  ResponseObject.swift
//  OpenAI
//
//  Created by Oleksii Nezhyborets on 27.03.2025.
//

import Foundation
import OpenAPIRuntime

/// Represents a model for querying the OpenAI API.
public struct ResponseObject: Codable, Equatable, Sendable {
    public typealias Schemas = Components.Schemas
    public typealias ResponseProperties = Schemas.ResponseProperties
    public typealias IncompleteDetails = Schemas.Response.Value3Payload.IncompleteDetailsPayload?
    public typealias Status = Schemas.Response.Value3Payload.StatusPayload
    public typealias Truncation = Schemas.ResponseProperties.TruncationPayload
    public typealias PromptCacheRetention = Schemas.ModelResponseProperties.PromptCacheRetentionPayload

    /// Whether to run the model response in the background.
    public let background: Bool?

    /// Unix timestamp (in seconds) of when this Response was completed.
    public let completedAt: Double?

    /// The conversation associated with this response.
    public let conversation: Schemas.Conversation2?

    /// Unix timestamp (in seconds) of when this Response was created.
    public let createdAt: Double

    /// An error object returned when the model fails to generate a Response.
    public let error: Schemas.ResponseError?

    /// Unique identifier for this Response.
    public let id: String

    /// Details about why the response is incomplete.
    public let incompleteDetails: IncompleteDetails?

    /// Inserts a system (or developer) message as the first item in the model's context.
    ///
    /// When using along with `previous_response_id`, the instructions from a previous response will not be carried over to the next response. This makes it simple to swap out system (or developer) messages in new responses.
    public let instructions: String?

    /// An upper bound for the number of tokens that can be generated for a response, including visible output tokens and [reasoning tokens](https://platform.openai.com/docs/guides/reasoning).
    public let maxOutputTokens: Int?

    /// The maximum number of tool calls that can be made during a model response.
    public let maxToolCalls: Int?

    /// Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard.
    ///
    /// Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters.
    public let metadata: [String: String]

    /// Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI offers a wide range of models with different capabilities, performance characteristics, and price points. Refer to the [model guide](https://platform.openai.com/docs/models) to browse and compare available models.
    ///
    /// Typed as `String` rather than the spec's `ModelIdsResponses` enum because the API returns arbitrary model strings (including `ResponsesOnlyModel` variants) and an open-ended string avoids breaking changes as new models are added.
    public let model: String

    /// The object type of this resource - always set to `response`.
    public let object: String

    /// An array of content items generated by the model.
    /// * The length and order of items in the `output` array is dependent on the model's response.
    /// * Rather than accessing the first item in the `output` array and assuming it's an `assistant` message with the content generated by the model, you might consider using the `output_text` property where supported in SDKs.
    public let output: [OutputItem]

    /// The concatenated text output from all `output_text` items in the `output` array, if any.
    public let outputText: String?

    /// Whether to allow the model to run tool calls in parallel.
    public let parallelToolCalls: Bool

    /// The unique ID of the previous response to the model. Use this to create multi-turn conversations. Learn more about [conversation state](https://platform.openai.com/docs/guides/conversation-state).
    public let previousResponseId: String?

    /// The prompt template and its variables used to generate this response, if any.
    public let prompt: Schemas.Prompt?

    /// Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the deprecated `user` field. [Learn more](https://platform.openai.com/docs/guides/prompt-caching).
    public let promptCacheKey: String?

    /// The retention policy for the prompt cache.
    public let promptCacheRetention: PromptCacheRetention?

    /// **o-series models only**
    ///
    /// Configuration options for [reasoning models](https://platform.openai.com/docs/guides/reasoning).
    public let reasoning: Schemas.Reasoning?

    /// A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).
    public let safetyIdentifier: String?

    /// Specifies the latency tier to use for processing the request.
    public let serviceTier: Schemas.ServiceTier?

    /// The status of the response generation. One of `completed`, `failed`, `in_progress`, `cancelled`, `queued`, or `incomplete`.
    public let status: Status?

    /// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or `top_p` but not both.
    public let temperature: Double?

    /// Configuration options for a text response from the model. Can be plain text or structured JSON data. Learn more:
    /// - [Text inputs and outputs](https://platform.openai.com/docs/guides/text)
    /// - [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs)
    public let text: Schemas.ResponseTextParam?

    /// How the model should select which tool (or tools) to use when generating a response. See the `tools` parameter to see how to specify which tools the model can call.
    public let toolChoice: Schemas.ToolChoiceParam?

    /// An array of tools the model may call while generating a response. You can specify which tool to use by setting the `tool_choice` parameter.
    ///
    /// The two categories of tools you can provide the model are:
    /// - **Built-in tools:** Tools that are provided by OpenAI that extend the model's capabilities, like [web search](https://platform.openai.com/docs/guides/tools-web-search) or [file search](https://platform.openai.com/docs/guides/tools-file-search). Learn more about [built-in tools](https://platform.openai.com/docs/guides/tools).
    /// - **Function calls (custom tools):** Functions that are defined by you, enabling the model to call your own code. Learn more about [function calling](https://platform.openai.com/docs/guides/function-calling).
    public let tools: [Tool]

    /// The number of top log probabilities to return for each output token.
    public let topLogprobs: Int?

    /// An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
    ///
    /// We generally recommend altering this or `temperature` but not both.
    public let topP: Double?

    /// The truncation strategy to use for the model response.
    ///
    /// - `auto`: If the input to this response exceeds the model's context window size, the model will truncate the response to fit the context window by dropping items from the beginning of the conversation.
    /// - `disabled` (default): If a model response will exceed the context window size for a model, the request will fail with a 400 error.
    public let truncation: Truncation?

    /// Represents token usage details including input tokens, output tokens, a breakdown of output tokens, and the total tokens used.
    /// [The Response Object API Reference Page](https://platform.openai.com/docs/api-reference/responses/object) says that the type of the field is Object, aka non-optional
    /// But an example of [Streaming's response.created] shows that `usage` can be null. And a the moment we use this struct for both regulard and streaming replies.
    public let usage: Schemas.ResponseUsage?

    /// A stable identifier for your end-user.
    ///
    /// API reference declares that it's type is non-optional string, but the example they provide shows that it can be null.
    @available(*, deprecated, message: "Use safetyIdentifier or promptCacheKey instead.")
    public let user: String?

    private enum CodingKeys: String, CodingKey {
        case background
        case completedAt = "completed_at"
        case conversation
        case createdAt = "created_at"
        case error
        case id
        case incompleteDetails = "incomplete_details"
        case instructions
        case maxOutputTokens = "max_output_tokens"
        case maxToolCalls = "max_tool_calls"
        case metadata
        case model
        case object
        case output
        case outputText = "output_text"
        case parallelToolCalls = "parallel_tool_calls"
        case previousResponseId = "previous_response_id"
        case prompt
        case promptCacheKey = "prompt_cache_key"
        case promptCacheRetention = "prompt_cache_retention"
        case reasoning
        case safetyIdentifier = "safety_identifier"
        case serviceTier = "service_tier"
        case status
        case temperature
        case text
        case toolChoice = "tool_choice"
        case tools
        case topLogprobs = "top_logprobs"
        case topP = "top_p"
        case truncation
        case usage
        case user
    }
}
